name: Publish NuGet
on:
    push:
        branches:
            - main
        paths:
            - version.props
            - .github/workflows/nuget.yml
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup .NET
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: 7.x

            - name: Publish NuGet Clients Common
              uses: ensersoft/action-nuget-publish@v1.0.2
              with:
                  nuget-key: ${{ secrets.NUGET_API_KEY }}
                  project: src/Ensersoft.Clients.Common/Ensersoft.Clients.Common.csproj

            - name: Publish NuGet Predictor Abstractions
              uses: ensersoft/action-nuget-publish@v1.0.2
              with:
                  nuget-key: ${{ secrets.NUGET_API_KEY }}
                  project: src/Ensersoft.Clients.Predictor.Abstractions/Ensersoft.Clients.Predictor.Abstractions.csproj

            - name: Publish NuGet Predictions Abstractions
              uses: ensersoft/action-nuget-publish@v1.0.2
              with:
                  nuget-key: ${{ secrets.NUGET_API_KEY }}
                  project: src/Ensersoft.Clients.Predictions.Abstractions/Ensersoft.Clients.Predictions.Abstractions.csproj

            - name: Publish NuGet Notifications Abstractions
              uses: ensersoft/action-nuget-publish@v1.0.2
              with:
                  nuget-key: ${{ secrets.NUGET_API_KEY }}
                  project: src/Ensersoft.Clients.Notifications.Abstractions/Ensersoft.Clients.Notifications.Abstractions.csproj

            - name: Publish NuGet Scrappers Abstractions
              uses: ensersoft/action-nuget-publish@v1.0.2
              with:
                  nuget-key: ${{ secrets.NUGET_API_KEY }}
                  project: src/Ensersoft.Clients.Scrappers.Abstractions/Ensersoft.Clients.Scrappers.Abstractions.csproj

            - name: Publish NuGet WebApi Abstractions
              uses: ensersoft/action-nuget-publish@v1.0.2
              with:
                  nuget-key: ${{ secrets.NUGET_API_KEY }}
                  project: src/Ensersoft.Clients.WebApi.Abstractions/Ensersoft.Clients.WebApi.Abstractions.csproj

            - name: Publish NuGet Predictor
              uses: ensersoft/action-nuget-publish@v1.0.2
              with:
                  nuget-key: ${{ secrets.NUGET_API_KEY }}
                  project: src/Ensersoft.Clients.Predictor/Ensersoft.Clients.Predictor.csproj

            - name: Publish NuGet Predictions
              uses: ensersoft/action-nuget-publish@v1.0.2
              with:
                  nuget-key: ${{ secrets.NUGET_API_KEY }}
                  project: src/Ensersoft.Clients.Predictions/Ensersoft.Clients.Predictions.csproj

            - name: Publish NuGet Notifications
              uses: ensersoft/action-nuget-publish@v1.0.2
              with:
                  nuget-key: ${{ secrets.NUGET_API_KEY }}
                  project: src/Ensersoft.Clients.Notifications/Ensersoft.Clients.Notifications.csproj

            - name: Publish NuGet Scrappers
              uses: ensersoft/action-nuget-publish@v1.0.2
              with:
                  nuget-key: ${{ secrets.NUGET_API_KEY }}
                  project: src/Ensersoft.Clients.Scrappers/Ensersoft.Clients.Scrappers.csproj

            - name: Publish NuGet WebApi
              uses: ensersoft/action-nuget-publish@v1.0.2
              with:
                  nuget-key: ${{ secrets.NUGET_API_KEY }}
                  project: src/Ensersoft.Clients.WebApi/Ensersoft.Clients.WebApi.csproj